spring:
  rabbitmq:
    host: 192.168.10.34
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      ack:
        enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

