server:
  port: 8762

spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  redis:
    hostName: 192.168.10.34
    port: 6379
    database: 2
    password:
    pool:
      maxActive: 8
      maxWait: -1
      maxIdle: 100
      minIdle: 0
    timeout: 5000
  output:
    ansi:
      enabled: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/